SELECT r1.FOOD_TYPE, r1.REST_ID, r1.REST_NAME, r1.FAVORITES
FROM REST_INFO as r1, (
    SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) as r2
WHERE r1.FOOD_TYPE = r2.FOOD_TYPE
AND r1.FAVORITES = r2.FAVORITES
ORDER BY r1.FOOD_TYPE DESC