-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, 
    CONCAT(u.CITY, " ", u.STREET_ADDRESS1, " ", u.STREET_ADDRESS2) as 전체주소, 
    CONCAT(LEFT(TLNO, 3), "-", SUBSTRING(TLNO, 4, 4), "-", RIGHT(TLNO, 4)) as 전화번호
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
GROUP BY b.WRITER_ID
HAVING COUNT(b.WRITER_ID) >= 3
ORDER BY u.USER_ID DESC