-- 코드를 입력하세요
SELECT f.FLAVOR
FROM FIRST_HALF f JOIN (SELECT MIN(SHIPMENT_ID) as SHIPMENT_ID, SUM(TOTAL_ORDER) as ORDER_SUM
    FROM JULY
    GROUP BY FLAVOR) j
ON f.SHIPMENT_ID = j.SHIPMENT_ID
ORDER BY f.TOTAL_ORDER + j.ORDER_SUM DESC
LIMIT 3