-- 코드를 입력하세요
SELECT b.CATEGORY as CATEGORY, SUM(s.s_sum) as TOTAL_SALES
FROM BOOK b JOIN (SELECT BOOK_ID, sum(SALES) as s_sum
    FROM BOOK_SALES 
    WHERE date_format(SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY BOOK_ID) s
ON b.BOOK_ID = s.BOOK_ID
GROUP BY b.CATEGORY
ORDER BY CATEGORY