SELECT ANIMAL_ID, NAME,
    CASE
		WHEN SUBSTRING_INDEX(SEX_UPON_INTAKE, ' ', 1) = 'Neutered'
		THEN 'O'
		WHEN SUBSTRING_INDEX(SEX_UPON_INTAKE, ' ', 1) = 'Spayed'
		THEN 'O'
		ELSE 'X'
    END as 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID