

SELECT t.INGREDIENT_TYPE, SUM(t.TOTAL_ORDER) as TOTAL_ORDER
FROM (SELECT f.SHIPMENT_ID, f.FLAVOR, f.TOTAL_ORDER, i.INGREDIENT_TYPE
    FROM FIRST_HALF f join ICECREAM_INFO i
    ON f.FLAVOR = i.FLAVOR) as t
GROUP BY t.INGREDIENT_TYPE
ORDER BY t.TOTAL_ORDER