SELECT t.REST_ID, t.REST_NAME, t.FOOD_TYPE, t.FAVORITES, t.ADDRESS, t.SCORE
FROM (
    SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE),2) SCORE
    FROM REST_INFO i LEFT JOIN REST_REVIEW r
    ON i.REST_ID = r.REST_ID
    WHERE i.ADDRESS LIKE ('서울%')
    GROUP BY i.REST_ID) t
WHERE t.SCORE is not NULL
ORDER BY t.SCORE DESC, t.FAVORITES DESC


